name: Workflow
on:
  push:
    branches:
      - feature/devsecops-example2

      
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:

    
      - name: Hola Mundo
        run: |
          echo 'Hola Mundo'

  TESTING:
    runs-on: ubuntu-latest
    steps:

    
      - name: Hola Mundo
        run: |
          echo 'Hola Mundo'
        

  DEPLOY:
    runs-on: ubuntu-latest
    steps:

    
      - name: Hola Mundo
        run: |
          echo 'Hola Mundo'
                                  